-- 조건: NULL인 데이터는 10으로 계산 / 10이하 
-- 테이블: FISH_INFO

SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO
WHERE (LENGTH <= 10 OR LENGTH IS NULL);
-- 테스트 2번 틀림

SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO
WHERE LENGTH IS NULL;
-- 100점...?